# Generated by Django 5.1 on 2024-09-08 10:23

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_mysql.models.EnumField(choices=[('LONG_MOMENTUM_CALL', 'LONG_MOMENTUM_CALL'), ('LONG_MOMENTUM_PUT', 'LONG_MOMENTUM_PUT'), ('SHORT_STRANGLE', 'SHORT_STRANGLE')])),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', django_mysql.models.EnumField(choices=[('ZERODHA', 'ZERODHA'), ('UPSTOX', 'UPSTOX'), ('BROKER_SIMULATOR', 'BROKER_SIMULATOR')])),
                ('state', django_mysql.models.EnumField(choices=[('CREATED', 'CREATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')])),
                ('day', models.DateField()),
                ('initiation_time', models.TimeField()),
                ('completion_time', models.TimeField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', related_query_name='trade', to='trading.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_txn_id', models.CharField(max_length=50)),
                ('txn_type', django_mysql.models.EnumField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')])),
                ('instrument_symbol', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price_type', django_mysql.models.EnumField(choices=[('BUY', 'MARKET'), ('SELL', 'LIMIT')])),
                ('status', django_mysql.models.EnumField(choices=[('CREATED', 'CREATED'), ('BROKER_PENDING', 'BROKER_PENDING'), ('CONFIRMED', 'CONFIRMED')])),
                ('order_request_time', models.TimeField()),
                ('order_request_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_confirmation_time', models.TimeField()),
                ('order_confirmation_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tot_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='trading.trade')),
            ],
        ),
    ]
